### ISSUE TITLE
Set up your Kanban board

### ISSUE THREAD

**Issue by aboongm** [aboongm/Catalog-of-my-things#22]
- Github project link:
 https://github.com/aboongm/Catalog-of-my-things/projects/1

- There are four members in your team

Team Member #1 : @aboongm 
Team member #2 : @tylher 
Team member #3 : @misheck12 
Team member #4 : @sainingo

**Comment by TedLivist** [comment]
## STATUS: APPROVED ✔️ ✔️

Hi Team,

✔️ Tasks are assigned
✔️ All tasks descriptions were added

Your project is complete!  There is nothing else to say other than... it's time to go ahead with the project :shipit: 
Congratulations! 🎉

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
